#
# linux/drivers/rknand/Makefile
#
# $Id: Makefile,v 1.3 2011/01/21 10:12:56 Administrator Exp $
#


obj-$(CONFIG_MTD_NAND_RK29XX)		+= rknand_base_ko.o

#rk29xxnand-objs := rknand_base_ko.o flash.o ftl.o rknand_buffer.o emmc.o



